### PR TITLE
add cartesian_3d field support

### PR DESCRIPTION
**Pull request by zhaozhiwen**
A file fields/symmetries/cartesian_3d.cc and a few files under fields are modified. some details below

// 3D field in cartesian coordinates. Field itself is in cartesian coordinates.
// Dependent on 3 cartesian coordinates (Y, X, Z)
// The values can be loaded from the map in any order as long as their speed is ordered.
// The values are indexed as B1_3D[X][Y][Z],B2_3D[X][Y][Z],B3_3D[X][Y][Z]
// The field is three dimensional, ordered in the class as B1=Bx, B2=By, B3=Bz

//symmetry "cartesian_3D" is for full 3D map
//symmetry "cartesian_3D_quadrant" is for 3D map covering only the 1st quadrant where x>=0 && y>=0

### CODE REVIEW

**Comment by zhaozhiwen** [comment]
A file fields/symmetries/cartesian_3d.cc and a few files under fields are modified.  some details below

// 3D field in cartesian coordinates. Field itself is in cartesian coordinates.
// Dependent on 3 cartesian coordinates (Y, X, Z) 
// The values can be loaded from the map in any order as long as their speed is ordered.
// The values are indexed as B1_3D[X][Y][Z],B2_3D[X][Y][Z],B3_3D[X][Y][Z]
// The field is three dimensional, ordered in the class as B1=Bx, B2=By, B3=Bz

//symmetry "cartesian_3D" is for full 3D map
//symmetry "cartesian_3D_quadrant" is for 3D map covering only the 1st quadrant where x>=0 && y>=0

**Comment by maureeungaro** [comment]
One more comment: I see endMap being defined but not used.

**Comment by zhaozhiwen** [comment]
endMap is used in cartesian_3d.cc

**Comment by maureeungaro** [comment]
endMap is used in cartesian_3d.cc but it is added for the other configurations as well w/o being used. It's a small thing but good practice to either use it in the code or not define at all when is not used.

**Comment by zhaozhiwen** [comment]
totally agree, I added it thinking it would be convenient to use for any future map type, but I didn't want to touch existing map type. I can remove endMap from the general file and only use it for cartesian_3d if you want.

**Comment by maureeungaro** [comment]
yeah lets do that for now. These routines in general could use some improvements later on anyway.

**Comment by zhaozhiwen** [comment]
ok, I am at SPIN2018 now, I will remove endmap after back home next Wed

**Comment by maureeungaro** [comment]
It's ok let me merge it for now.

**Pull request merged**
