### PR TITLE
DC hit process proposed changes and comments

### PR DESCRIPTION
**Pull request by mestayer**
I made a number of comments all preceded by the string 'mac'

### CODE REVIEW

**Comment by mestayer** [comment]
@dlersch Daniel; would you take a look at my comments and we can discuss them?

**Comment by dlersch** [comment]
@mestayer Dear Mac, let me know when you are free and we can discuss your comments

**Comment by mestayer** [comment]
Now is a good time - Mac

----- Original Message -----

**Comment by maureeungaro** [comment]
Daniel implemented these changes.

**Pull request closed without merging**
